### ISSUE TITLE
how do i fork

### ISSUE THREAD

**Issue by claimholder** [netcord-team/netcord#6]
helppp

**Comment by usefulstuffs** [comment]
There's a button for that

**Comment by inori-aizawa** [comment]
![Screenshot 2024-03-17 090121](https://github.com/netcord-team/netcord/assets/155257081/65eb91be-6689-43a7-a3f7-9bc686c96955)
yes

**Comment by errortek** [comment]
> ![Screenshot 2024-03-17 090121](https://private-user-images.githubusercontent.com/155257081/313454983-65eb91be-6689-43a7-a3f7-9bc686c96955.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NjMxOTYsIm5iZiI6MTcxMDY2Mjg5NiwicGF0aCI6Ii8xNTUyNTcwODEvMzEzNDU0OTgzLTY1ZWI5MWJlLTY2ODktNDNhNy1hM2Y3LTliYzY4NmM5Njk1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QwODA4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzI2NTMyOThlYjIxMTcxOGU3MmI0YjBjOTI4M2YwNTA4MzFlYzg4YWNmNWI2NjgzNGM5NGQyNTkxNzllMTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u-6BVfDGZQUYqvDKjA9k30IVV3wu7Yn1EH25ypqjkNI) yes

fr

**Comment by errortek** [comment]
I think this was solved, so I closed the issue @inori-aizawa
